// infoq-scaffold-frontend-vue/src/views/monitor/job/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true">
            <el-form-item label="任务名称" prop="jobName">
              <el-input v-model="queryParams.jobName" placeholder="请输入任务名称" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="任务分组" prop="jobGroup">
              <el-select v-model="queryParams.jobGroup" placeholder="任务分组" clearable>
                <el-option v-for="dict in sys_job_group" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item label="任务状态" prop="status">
              <el-select v-model="queryParams.status" placeholder="任务状态" clearable>
                <el-option v-for="dict in sys_job_status" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:job:add']" type="primary" plain icon="Plus" @click="handleAdd">新增</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:job:edit']" type="success" plain icon="Edit" :disabled="single" @click="handleUpdate()">
              修改
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:job:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
              删除
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:job:export']" type="warning" plain icon="Download" @click="handleExport">导出</el-button>
          </el-col>
          <right-toolbar v-model:show-search="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table v-loading="loading" :data="jobList" border @selection-change="handleSelectionChange">
        <el-table-column type="selection" width="55" align="center" />
        <el-table-column label="任务ID" align="center" prop="jobId" width="110" />
        <el-table-column label="任务名称" align="center" prop="jobName" min-width="160" :show-overflow-tooltip="true" />
        <el-table-column label="任务分组" align="center" prop="jobGroup" width="120">
          <template #default="scope">
            <dict-tag :options="sys_job_group" :value="scope.row.jobGroup" />
          </template>
        </el-table-column>
        <el-table-column label="处理器" align="center" prop="handlerKey" min-width="160" :show-overflow-tooltip="true" />
        <el-table-column label="Cron表达式" align="center" prop="cronExpression" min-width="170" :show-overflow-tooltip="true" />
        <el-table-column label="错过策略" align="center" width="120">
          <template #default="scope">
            <dict-tag :options="sys_job_misfire_policy" :value="scope.row.misfirePolicy" />
          </template>
        </el-table-column>
        <el-table-column label="并发策略" align="center" width="120">
          <template #default="scope">
            <dict-tag :options="sys_job_concurrent" :value="scope.row.concurrent" />
          </template>
        </el-table-column>
        <el-table-column label="任务状态" align="center" width="120">
          <template #default="scope">
            <el-switch
              v-model="scope.row.status"
              active-value="0"
              inactive-value="1"
              v-hasPermi="['monitor:job:changeStatus']"
              @change="handleStatusChange(scope.row)"
            />
          </template>
        </el-table-column>
        <el-table-column label="备注" align="center" prop="remark" min-width="150" :show-overflow-tooltip="true" />
        <el-table-column label="操作" align="center" class-name="small-padding fixed-width" width="180">
          <template #default="scope">
            <el-tooltip content="执行一次" placement="top">
              <el-button v-hasPermi="['monitor:job:run']" link type="primary" icon="VideoPlay" @click="handleRun(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip content="修改" placement="top">
              <el-button v-hasPermi="['monitor:job:edit']" link type="primary" icon="Edit" @click="handleUpdate(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip content="删除" placement="top">
              <el-button v-hasPermi="['monitor:job:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)"></el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
    </el-card>

    <el-dialog v-model="dialog.visible" :title="dialog.title" width="640px" append-to-body>
      <el-form ref="jobFormRef" :model="form" :rules="rules" label-width="110px">
        <el-form-item label="任务名称" prop="jobName">
          <el-input v-model="form.jobName" placeholder="请输入任务名称" />
        </el-form-item>
        <el-form-item label="任务分组" prop="jobGroup">
          <el-select v-model="form.jobGroup" placeholder="请选择任务分组">
            <el-option v-for="dict in sys_job_group" :key="dict.value" :label="dict.label" :value="dict.value" />
          </el-select>
        </el-form-item>
        <el-form-item label="处理器标识" prop="handlerKey">
          <el-select v-model="form.handlerKey" placeholder="请选择处理器">
            <el-option v-for="item in handlerOptions" :key="item" :label="item" :value="item" />
          </el-select>
        </el-form-item>
        <el-form-item label="处理器参数" prop="handlerParams">
          <el-input v-model="form.handlerParams" type="textarea" :rows="4" placeholder='请输入JSON对象，例如 {"source":"manual"}' />
        </el-form-item>
        <el-form-item label="Cron表达式" prop="cronExpression">
          <el-input v-model="form.cronExpression" placeholder="例如 0 0/30 * * * ?" />
        </el-form-item>
        <el-form-item label="错过策略" prop="misfirePolicy">
          <el-radio-group v-model="form.misfirePolicy">
            <el-radio v-for="dict in sys_job_misfire_policy" :key="dict.value" :value="dict.value">{{ dict.label }}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="并发策略" prop="concurrent">
          <el-radio-group v-model="form.concurrent">
            <el-radio v-for="dict in sys_job_concurrent" :key="dict.value" :value="dict.value">{{ dict.label }}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="任务状态" prop="status">
          <el-radio-group v-model="form.status">
            <el-radio v-for="dict in sys_job_status" :key="dict.value" :value="dict.value">{{ dict.label }}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="备注" prop="remark">
          <el-input v-model="form.remark" type="textarea" :rows="2" placeholder="请输入备注" />
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button :loading="buttonLoading" type="primary" @click="submitForm">确定</el-button>
          <el-button @click="cancel">取消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="Job" lang="ts">
import { addJob, changeJobStatus, delJob, getJob, listJob, listJobHandlerKeys, runJob, updateJob } from '@/api/monitor/job';
import type { JobForm, JobQuery, JobVO } from '@/api/monitor/job/types';
import { toDictRefs } from '@/utils/dict';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_job_group } = toDictRefs((proxy?.useDict('sys_job_group') ?? {}) as Record<'sys_job_group', DictDataOption[]>);
const { sys_job_status } = toDictRefs((proxy?.useDict('sys_job_status') ?? {}) as Record<'sys_job_status', DictDataOption[]>);
const { sys_job_misfire_policy } = toDictRefs((proxy?.useDict('sys_job_misfire_policy') ?? {}) as Record<'sys_job_misfire_policy', DictDataOption[]>);
const { sys_job_concurrent } = toDictRefs((proxy?.useDict('sys_job_concurrent') ?? {}) as Record<'sys_job_concurrent', DictDataOption[]>);

const loading = ref(true);
const buttonLoading = ref(false);
const showSearch = ref(true);
const total = ref(0);
const single = ref(true);
const multiple = ref(true);
const ids = ref<Array<number | string>>([]);
const jobList = ref<JobVO[]>([]);
const handlerOptions = ref<string[]>([]);

const queryFormRef = ref<ElFormInstance>();
const jobFormRef = ref<ElFormInstance>();

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

const initFormData: JobForm = {
  jobId: undefined,
  jobName: '',
  jobGroup: 'SYSTEM',
  handlerKey: '',
  handlerParams: '{}',
  cronExpression: '0 0/30 * * * ?',
  misfirePolicy: '0',
  concurrent: '1',
  status: '1',
  remark: ''
};

const data = reactive<PageData<JobForm, JobQuery>>({
  form: { ...initFormData },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    jobName: '',
    jobGroup: '',
    handlerKey: '',
    status: ''
  },
  rules: {
    jobName: [{ required: true, message: '任务名称不能为空', trigger: 'blur' }],
    jobGroup: [{ required: true, message: '任务分组不能为空', trigger: 'change' }],
    handlerKey: [{ required: true, message: '处理器标识不能为空', trigger: 'change' }],
    handlerParams: [{ required: true, message: '处理器参数不能为空', trigger: 'blur' }],
    cronExpression: [{ required: true, message: 'Cron表达式不能为空', trigger: 'blur' }],
    misfirePolicy: [{ required: true, message: '错过策略不能为空', trigger: 'change' }],
    concurrent: [{ required: true, message: '并发策略不能为空', trigger: 'change' }],
    status: [{ required: true, message: '任务状态不能为空', trigger: 'change' }]
  }
});

const { queryParams, form, rules } = toRefs(data);

const getHandlerOptions = async () => {
  const res = await listJobHandlerKeys();
  handlerOptions.value = res.data || [];
  if (!form.value.handlerKey && handlerOptions.value.length > 0) {
    form.value.handlerKey = handlerOptions.value[0];
  }
};

const getList = async () => {
  loading.value = true;
  const res = await listJob(queryParams.value);
  jobList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};

const cancel = () => {
  reset();
  dialog.visible = false;
};

const reset = () => {
  form.value = { ...initFormData };
  jobFormRef.value?.resetFields();
  if (handlerOptions.value.length > 0) {
    form.value.handlerKey = handlerOptions.value[0];
  }
};

const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};

const resetQuery = () => {
  queryFormRef.value?.resetFields();
  handleQuery();
};

const handleSelectionChange = (selection: JobVO[]) => {
  ids.value = selection.map((item) => item.jobId);
  single.value = selection.length !== 1;
  multiple.value = !selection.length;
};

const handleAdd = () => {
  reset();
  dialog.visible = true;
  dialog.title = '新增定时任务';
};

const handleUpdate = async (row?: JobVO) => {
  reset();
  const jobId = row?.jobId || ids.value[0];
  const res = await getJob(jobId);
  Object.assign(form.value, res.data);
  dialog.visible = true;
  dialog.title = '修改定时任务';
};

const submitForm = () => {
  jobFormRef.value?.validate(async (valid: boolean) => {
    if (!valid) {
      return;
    }
    buttonLoading.value = true;
    try {
      if (form.value.jobId) {
        await updateJob(form.value);
      } else {
        await addJob(form.value);
      }
      proxy?.$modal.msgSuccess('操作成功');
      dialog.visible = false;
      await getList();
    } finally {
      buttonLoading.value = false;
    }
  });
};

const handleDelete = async (row?: JobVO) => {
  const jobIds = row?.jobId || ids.value;
  await proxy?.$modal.confirm('是否确认删除任务编号为"' + jobIds + '"的数据项？');
  await delJob(jobIds);
  proxy?.$modal.msgSuccess('删除成功');
  await getList();
};

const handleExport = () => {
  proxy?.download('monitor/job/export', { ...queryParams.value }, `job_${new Date().getTime()}.xlsx`);
};

const handleStatusChange = async (row: JobVO) => {
  const text = row.status === '0' ? '启用' : '暂停';
  try {
    await proxy?.$modal.confirm('确认要' + text + '任务"' + row.jobName + '"吗？');
    await changeJobStatus(row.jobId, row.status);
    proxy?.$modal.msgSuccess(text + '成功');
  } catch (error) {
    row.status = row.status === '0' ? '1' : '0';
  }
};

const handleRun = async (row: JobVO) => {
  await proxy?.$modal.confirm('确认立即执行任务"' + row.jobName + '"一次吗？');
  await runJob(row.jobId);
  proxy?.$modal.msgSuccess('执行请求已提交');
};

onMounted(async () => {
  await getHandlerOptions();
  await getList();
});
</script>

// infoq-scaffold-frontend-react/src/pages/monitor/job/index.tsx
import { useCallback, useEffect, useState } from 'react';
import { DeleteOutlined, DownloadOutlined, EditOutlined, PlayCircleOutlined, PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { Button, Card, Col, Form, Input, Modal, Radio, Row, Select, Space, Switch, Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import useDictOptions from '@/hooks/useDictOptions';
import { addJob, changeJobStatus, delJob, getJob, listJob, listJobHandlerKeys, runJob, updateJob } from '@/api/monitor/job';
import type { JobForm, JobQuery, JobVO } from '@/api/monitor/job/types';
import DictTag from '@/components/DictTag';
import Pagination from '@/components/Pagination';
import RightToolbar from '@/components/RightToolbar';
import auth from '@/utils/permission';
import modal from '@/utils/modal';
import { download } from '@/utils/request';

const initialQuery: JobQuery = {
  pageNum: 1,
  pageSize: 10,
  jobName: '',
  jobGroup: '',
  handlerKey: '',
  status: ''
};

const initialForm: JobForm = {
  jobId: undefined,
  jobName: '',
  jobGroup: 'SYSTEM',
  handlerKey: '',
  handlerParams: '{}',
  cronExpression: '0 0/30 * * * ?',
  misfirePolicy: '0',
  concurrent: '1',
  status: '1',
  remark: ''
};

export default function JobPage() {
  const [query, setQuery] = useState<JobQuery>(initialQuery);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [list, setList] = useState<JobVO[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [handlerOptions, setHandlerOptions] = useState<string[]>([]);
  const [form] = Form.useForm<JobForm>();
  const editingJobId = Form.useWatch('jobId', form);
  const dict = useDictOptions('sys_job_group', 'sys_job_status', 'sys_job_misfire_policy', 'sys_job_concurrent');

  const loadList = useCallback(async (nextQuery: JobQuery) => {
    setLoading(true);
    try {
      const response = await listJob(nextQuery);
      setList(response.rows);
      setTotal(response.total ?? response.rows.length);
    } finally {
      setLoading(false);
    }
  }, []);

  const loadHandlerOptions = useCallback(async () => {
    const response = await listJobHandlerKeys();
    const nextOptions = response.data || [];
    setHandlerOptions(nextOptions);
    const currentKey = form.getFieldValue('handlerKey');
    if (!currentKey && nextOptions.length > 0) {
      form.setFieldValue('handlerKey', nextOptions[0]);
    }
  }, [form]);

  useEffect(() => {
    loadList(initialQuery);
    loadHandlerOptions();
  }, [loadList, loadHandlerOptions]);

  const handleStatusToggle = async (record: JobVO, checked: boolean) => {
    const nextStatus = checked ? '0' : '1';
    const label = nextStatus === '0' ? '启用' : '暂停';
    const confirmed = await modal.confirm(`确认要${label}任务 "${record.jobName}" 吗？`);
    if (!confirmed) {
      return;
    }
    await changeJobStatus(record.jobId, nextStatus);
    modal.msgSuccess(`${label}成功`);
    loadList(query);
  };

  const columns: ColumnsType<JobVO> = [
    { title: '任务ID', dataIndex: 'jobId', align: 'center', width: 110 },
    { title: '任务名称', dataIndex: 'jobName', align: 'center' },
    {
      title: '任务分组',
      dataIndex: 'jobGroup',
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_job_group || []} value={value} />
    },
    { title: '处理器', dataIndex: 'handlerKey', align: 'center' },
    { title: 'Cron表达式', dataIndex: 'cronExpression', align: 'center' },
    {
      title: '错过策略',
      dataIndex: 'misfirePolicy',
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_job_misfire_policy || []} value={value} />
    },
    {
      title: '并发策略',
      dataIndex: 'concurrent',
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_job_concurrent || []} value={value} />
    },
    {
      title: '任务状态',
      dataIndex: 'status',
      align: 'center',
      render: (value: string, record) => (
        <Switch
          checked={value === '0'}
          disabled={!auth.hasPermiOr(['monitor:job:changeStatus'])}
          onChange={(checked) => handleStatusToggle(record, checked)}
        />
      )
    },
    { title: '备注', dataIndex: 'remark', align: 'center' },
    {
      title: '操作',
      key: 'action',
      align: 'center',
      render: (_, record) => (
        <Space size={4}>
          {auth.hasPermiOr(['monitor:job:run']) && (
            <Button className="table-action-link" type="link" icon={<PlayCircleOutlined />} onClick={() => handleRun(record.jobId, record.jobName)} />
          )}
          {auth.hasPermiOr(['monitor:job:edit']) && (
            <Button className="table-action-link" type="link" icon={<EditOutlined />} onClick={() => handleEdit(record.jobId)} />
          )}
          {auth.hasPermiOr(['monitor:job:remove']) && (
            <Button className="table-action-link" type="link" icon={<DeleteOutlined />} onClick={() => handleDelete(record.jobId)} />
          )}
        </Space>
      )
    }
  ];

  const handleSearch = () => {
    const next = { ...query, pageNum: 1 };
    setQuery(next);
    loadList(next);
  };

  const handleReset = () => {
    setQuery(initialQuery);
    loadList(initialQuery);
  };

  const handleAdd = () => {
    const nextForm = {
      ...initialForm,
      handlerKey: handlerOptions[0] || ''
    };
    form.setFieldsValue(nextForm);
    setDialogOpen(true);
  };

  const handleEdit = async (jobId?: string | number) => {
    if (!jobId) {
      return;
    }
    const response = await getJob(jobId);
    form.setFieldsValue({ ...initialForm, ...response.data });
    setDialogOpen(true);
  };

  const handleDelete = async (jobId?: string | number | Array<string | number>) => {
    const target = jobId || selectedIds;
    if (!target || (Array.isArray(target) && target.length === 0)) {
      modal.msgWarning('请选择要删除的任务');
      return;
    }
    const display = Array.isArray(target) ? target.join(',') : target;
    const confirmed = await modal.confirm(`是否确认删除任务编号为 "${display}" 的数据项？`);
    if (!confirmed) {
      return;
    }
    await delJob(target);
    modal.msgSuccess('删除成功');
    setSelectedIds([]);
    loadList(query);
  };

  const handleRun = async (jobId: string | number, jobName: string) => {
    const confirmed = await modal.confirm(`是否确认立即执行任务 "${jobName}" 一次？`);
    if (!confirmed) {
      return;
    }
    await runJob(jobId);
    modal.msgSuccess('执行请求已提交');
  };

  const handleSubmit = async () => {
    const values = await form.validateFields();
    setSubmitting(true);
    try {
      if (values.jobId) {
        await updateJob(values);
      } else {
        await addJob(values);
      }
      modal.msgSuccess('操作成功');
      setDialogOpen(false);
      loadList(query);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {showSearch && (
        <Card>
          <Form layout="inline" className="query-form">
            <Row gutter={16} style={{ width: '100%' }}>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="任务名称" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入任务名称"
                    value={query.jobName}
                    onChange={(event) => setQuery((prev) => ({ ...prev, jobName: event.target.value }))}
                    onPressEnter={handleSearch}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="任务分组" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    placeholder="任务分组"
                    style={{ width: '100%' }}
                    value={query.jobGroup || undefined}
                    options={(dict.sys_job_group || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, jobGroup: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="任务状态" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    placeholder="任务状态"
                    style={{ width: '100%' }}
                    value={query.status || undefined}
                    options={(dict.sys_job_status || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, status: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24}>
                <Form.Item style={{ marginBottom: 0 }}>
                  <Space>
                    <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                      搜索
                    </Button>
                    <Button icon={<ReloadOutlined />} onClick={handleReset}>
                      重置
                    </Button>
                  </Space>
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>
      )}

      <Card>
        <div className="table-toolbar">
          <Space wrap className="toolbar-buttons">
            {auth.hasPermiOr(['monitor:job:add']) && (
              <Button className="btn-plain-primary" icon={<PlusOutlined />} onClick={handleAdd}>
                新增
              </Button>
            )}
            {auth.hasPermiOr(['monitor:job:edit']) && (
              <Button
                className="btn-plain-success"
                icon={<EditOutlined />}
                onClick={() => handleEdit(selectedIds[0])}
                disabled={selectedIds.length !== 1}
              >
                修改
              </Button>
            )}
            {auth.hasPermiOr(['monitor:job:remove']) && (
              <Button className="btn-plain-danger" icon={<DeleteOutlined />} onClick={() => handleDelete()} disabled={selectedIds.length === 0}>
                删除
              </Button>
            )}
            {auth.hasPermiOr(['monitor:job:export']) && (
              <Button
                className="btn-plain-warning"
                icon={<DownloadOutlined />}
                onClick={() => download('/monitor/job/export', { ...query }, `job_${Date.now()}.xlsx`)}
              >
                导出
              </Button>
            )}
          </Space>
          <div className="right-toolbar-wrap">
            <RightToolbar showSearch={showSearch} onShowSearchChange={setShowSearch} onQueryTable={() => loadList(query)} />
          </div>
        </div>

        <Table<JobVO>
          rowKey="jobId"
          loading={loading}
          bordered
          columns={columns}
          dataSource={list}
          pagination={false}
          rowSelection={{ selectedRowKeys: selectedIds, onChange: (keys) => setSelectedIds(keys as Array<string | number>) }}
        />

        <Pagination
          total={total}
          page={query.pageNum}
          limit={query.pageSize}
          onPageChange={({ page, limit }) => {
            const next = { ...query, pageNum: page, pageSize: limit };
            setQuery(next);
            loadList(next);
          }}
        />
      </Card>

      <Modal
        open={dialogOpen}
        title={editingJobId ? '修改定时任务' : '新增定时任务'}
        confirmLoading={submitting}
        onCancel={() => setDialogOpen(false)}
        onOk={handleSubmit}
      >
        <Form form={form} layout="vertical" initialValues={initialForm}>
          <Form.Item label="任务名称" name="jobName" rules={[{ required: true, message: '任务名称不能为空' }]}>
            <Input />
          </Form.Item>
          <Form.Item label="任务分组" name="jobGroup" rules={[{ required: true, message: '任务分组不能为空' }]}>
            <Select options={(dict.sys_job_group || []).map((item) => ({ label: item.label, value: item.value }))} />
          </Form.Item>
          <Form.Item label="处理器标识" name="handlerKey" rules={[{ required: true, message: '处理器标识不能为空' }]}>
            <Select options={handlerOptions.map((item) => ({ label: item, value: item }))} />
          </Form.Item>
          <Form.Item label="处理器参数" name="handlerParams" rules={[{ required: true, message: '处理器参数不能为空' }]}>
            <Input.TextArea rows={4} />
          </Form.Item>
          <Form.Item label="Cron表达式" name="cronExpression" rules={[{ required: true, message: 'Cron表达式不能为空' }]}>
            <Input />
          </Form.Item>
          <Form.Item label="错过策略" name="misfirePolicy" rules={[{ required: true, message: '错过策略不能为空' }]}>
            <Radio.Group options={(dict.sys_job_misfire_policy || []).map((item) => ({ label: item.label, value: item.value }))} />
          </Form.Item>
          <Form.Item label="并发策略" name="concurrent" rules={[{ required: true, message: '并发策略不能为空' }]}>
            <Radio.Group options={(dict.sys_job_concurrent || []).map((item) => ({ label: item.label, value: item.value }))} />
          </Form.Item>
          <Form.Item label="任务状态" name="status" rules={[{ required: true, message: '任务状态不能为空' }]}>
            <Radio.Group options={(dict.sys_job_status || []).map((item) => ({ label: item.label, value: item.value }))} />
          </Form.Item>
          <Form.Item label="备注" name="remark">
            <Input.TextArea rows={2} />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  );
}
