// infoq-scaffold-frontend-vue/src/views/monitor/jobLog/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true">
            <el-form-item label="任务名称" prop="jobName">
              <el-input v-model="queryParams.jobName" placeholder="请输入任务名称" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="任务分组" prop="jobGroup">
              <el-select v-model="queryParams.jobGroup" placeholder="任务分组" clearable>
                <el-option v-for="dict in sys_job_group" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item label="执行状态" prop="status">
              <el-select v-model="queryParams.status" placeholder="执行状态" clearable>
                <el-option v-for="dict in sys_common_status" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:jobLog:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
              删除
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:jobLog:remove']" type="danger" plain icon="Delete" @click="handleClean">清空</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:jobLog:export']" type="warning" plain icon="Download" @click="handleExport">导出</el-button>
          </el-col>
          <right-toolbar v-model:show-search="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table v-loading="loading" :data="jobLogList" border @selection-change="handleSelectionChange">
        <el-table-column type="selection" width="55" align="center" />
        <el-table-column label="日志ID" align="center" prop="jobLogId" width="120" />
        <el-table-column label="任务名称" align="center" prop="jobName" min-width="160" :show-overflow-tooltip="true" />
        <el-table-column label="任务分组" align="center" width="120">
          <template #default="scope">
            <dict-tag :options="sys_job_group" :value="scope.row.jobGroup" />
          </template>
        </el-table-column>
        <el-table-column label="处理器" align="center" prop="handlerKey" min-width="150" :show-overflow-tooltip="true" />
        <el-table-column label="触发来源" align="center" prop="triggerSource" width="110" />
        <el-table-column label="执行状态" align="center" width="110">
          <template #default="scope">
            <dict-tag :options="sys_common_status" :value="scope.row.status" />
          </template>
        </el-table-column>
        <el-table-column label="耗时(毫秒)" align="center" prop="durationMs" width="120" />
        <el-table-column label="开始时间" align="center" prop="startTime" width="170" />
        <el-table-column label="结束时间" align="center" prop="endTime" width="170" />
        <el-table-column label="执行消息" align="center" prop="jobMessage" min-width="200" :show-overflow-tooltip="true" />
        <el-table-column label="异常信息" align="center" prop="exceptionInfo" min-width="220" :show-overflow-tooltip="true" />
      </el-table>

      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
    </el-card>
  </div>
</template>

<script setup name="JobLog" lang="ts">
import { cleanJobLog, delJobLog, listJobLog } from '@/api/monitor/jobLog';
import type { JobLogQuery, JobLogVO } from '@/api/monitor/jobLog/types';
import { toDictRefs } from '@/utils/dict';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_common_status } = toDictRefs((proxy?.useDict('sys_common_status') ?? {}) as Record<'sys_common_status', DictDataOption[]>);
const { sys_job_group } = toDictRefs((proxy?.useDict('sys_job_group') ?? {}) as Record<'sys_job_group', DictDataOption[]>);

const loading = ref(true);
const showSearch = ref(true);
const total = ref(0);
const multiple = ref(true);
const ids = ref<Array<number | string>>([]);
const jobLogList = ref<JobLogVO[]>([]);

const queryFormRef = ref<ElFormInstance>();

const queryParams = ref<JobLogQuery>({
  pageNum: 1,
  pageSize: 10,
  jobName: '',
  jobGroup: '',
  handlerKey: '',
  triggerSource: '',
  status: ''
});

const getList = async () => {
  loading.value = true;
  const res = await listJobLog(queryParams.value);
  jobLogList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};

const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};

const resetQuery = () => {
  queryFormRef.value?.resetFields();
  handleQuery();
};

const handleSelectionChange = (selection: JobLogVO[]) => {
  ids.value = selection.map((item) => item.jobLogId);
  multiple.value = !selection.length;
};

const handleDelete = async (row?: JobLogVO) => {
  const jobLogIds = row?.jobLogId || ids.value;
  await proxy?.$modal.confirm('是否确认删除任务日志编号为"' + jobLogIds + '"的数据项？');
  await delJobLog(jobLogIds);
  proxy?.$modal.msgSuccess('删除成功');
  await getList();
};

const handleClean = async () => {
  await proxy?.$modal.confirm('是否确认清空所有任务日志数据项？');
  await cleanJobLog();
  proxy?.$modal.msgSuccess('清空成功');
  await getList();
};

const handleExport = () => {
  proxy?.download('monitor/jobLog/export', { ...queryParams.value }, `jobLog_${new Date().getTime()}.xlsx`);
};

onMounted(() => {
  getList();
});
</script>

// infoq-scaffold-frontend-react/src/pages/monitor/jobLog/index.tsx
import { useCallback, useEffect, useState } from 'react';
import { DeleteOutlined, DownloadOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { Button, Card, Col, Form, Input, Row, Select, Space, Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import useDictOptions from '@/hooks/useDictOptions';
import { cleanJobLog, delJobLog, listJobLog } from '@/api/monitor/jobLog';
import type { JobLogQuery, JobLogVO } from '@/api/monitor/jobLog/types';
import DictTag from '@/components/DictTag';
import Pagination from '@/components/Pagination';
import RightToolbar from '@/components/RightToolbar';
import auth from '@/utils/permission';
import modal from '@/utils/modal';
import { download } from '@/utils/request';

const initialQuery: JobLogQuery = {
  pageNum: 1,
  pageSize: 10,
  jobName: '',
  jobGroup: '',
  handlerKey: '',
  triggerSource: '',
  status: ''
};

export default function JobLogPage() {
  const [query, setQuery] = useState<JobLogQuery>(initialQuery);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [list, setList] = useState<JobLogVO[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const dict = useDictOptions('sys_job_group', 'sys_common_status');

  const loadList = useCallback(async (nextQuery: JobLogQuery) => {
    setLoading(true);
    try {
      const response = await listJobLog(nextQuery);
      setList(response.rows);
      setTotal(response.total ?? response.rows.length);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadList(initialQuery);
  }, [loadList]);

  const columns: ColumnsType<JobLogVO> = [
    { title: '日志ID', dataIndex: 'jobLogId', align: 'center', width: 120 },
    { title: '任务名称', dataIndex: 'jobName', align: 'center' },
    {
      title: '任务分组',
      dataIndex: 'jobGroup',
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_job_group || []} value={value} />
    },
    { title: '处理器', dataIndex: 'handlerKey', align: 'center' },
    { title: '触发来源', dataIndex: 'triggerSource', align: 'center' },
    {
      title: '执行状态',
      dataIndex: 'status',
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_common_status || []} value={value} />
    },
    { title: '耗时(毫秒)', dataIndex: 'durationMs', align: 'center' },
    { title: '开始时间', dataIndex: 'startTime', align: 'center' },
    { title: '结束时间', dataIndex: 'endTime', align: 'center' },
    { title: '执行消息', dataIndex: 'jobMessage', align: 'center' },
    { title: '异常信息', dataIndex: 'exceptionInfo', align: 'center' }
  ];

  const handleSearch = () => {
    const next = { ...query, pageNum: 1 };
    setQuery(next);
    loadList(next);
  };

  const handleReset = () => {
    setQuery(initialQuery);
    loadList(initialQuery);
  };

  const handleDelete = async (jobLogId?: string | number | Array<string | number>) => {
    const target = jobLogId || selectedIds;
    if (!target || (Array.isArray(target) && target.length === 0)) {
      modal.msgWarning('请选择要删除的任务日志');
      return;
    }
    const display = Array.isArray(target) ? target.join(',') : target;
    const confirmed = await modal.confirm(`是否确认删除任务日志编号为 "${display}" 的数据项？`);
    if (!confirmed) {
      return;
    }
    await delJobLog(target);
    modal.msgSuccess('删除成功');
    setSelectedIds([]);
    loadList(query);
  };

  const handleClean = async () => {
    const confirmed = await modal.confirm('是否确认清空所有任务日志数据项？');
    if (!confirmed) {
      return;
    }
    await cleanJobLog();
    modal.msgSuccess('清空成功');
    loadList(query);
  };

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {showSearch && (
        <Card>
          <Form layout="inline" className="query-form">
            <Row gutter={16} style={{ width: '100%' }}>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="任务名称" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入任务名称"
                    value={query.jobName}
                    onChange={(event) => setQuery((prev) => ({ ...prev, jobName: event.target.value }))}
                    onPressEnter={handleSearch}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="任务分组" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    placeholder="任务分组"
                    style={{ width: '100%' }}
                    value={query.jobGroup || undefined}
                    options={(dict.sys_job_group || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, jobGroup: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="执行状态" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    placeholder="执行状态"
                    style={{ width: '100%' }}
                    value={query.status || undefined}
                    options={(dict.sys_common_status || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, status: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24}>
                <Form.Item style={{ marginBottom: 0 }}>
                  <Space>
                    <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                      搜索
                    </Button>
                    <Button icon={<ReloadOutlined />} onClick={handleReset}>
                      重置
                    </Button>
                  </Space>
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>
      )}

      <Card>
        <div className="table-toolbar">
          <Space wrap className="toolbar-buttons">
            {auth.hasPermiOr(['monitor:jobLog:remove']) && (
              <Button className="btn-plain-danger" icon={<DeleteOutlined />} onClick={() => handleDelete()} disabled={selectedIds.length === 0}>
                删除
              </Button>
            )}
            {auth.hasPermiOr(['monitor:jobLog:remove']) && (
              <Button className="btn-plain-danger" icon={<DeleteOutlined />} onClick={handleClean}>
                清空
              </Button>
            )}
            {auth.hasPermiOr(['monitor:jobLog:export']) && (
              <Button
                className="btn-plain-warning"
                icon={<DownloadOutlined />}
                onClick={() => download('/monitor/jobLog/export', { ...query }, `jobLog_${Date.now()}.xlsx`)}
              >
                导出
              </Button>
            )}
          </Space>
          <div className="right-toolbar-wrap">
            <RightToolbar showSearch={showSearch} onShowSearchChange={setShowSearch} onQueryTable={() => loadList(query)} />
          </div>
        </div>

        <Table<JobLogVO>
          rowKey="jobLogId"
          loading={loading}
          bordered
          columns={columns}
          dataSource={list}
          pagination={false}
          rowSelection={{ selectedRowKeys: selectedIds, onChange: (keys) => setSelectedIds(keys as Array<string | number>) }}
        />

        <Pagination
          total={total}
          page={query.pageNum}
          limit={query.pageSize}
          onPageChange={({ page, limit }) => {
            const next = { ...query, pageNum: page, pageSize: limit };
            setQuery(next);
            loadList(next);
          }}
        />
      </Card>
    </Space>
  );
}
