// infoq-scaffold-frontend-react/src/pages/system/user/index.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Button,
  Card,
  Checkbox,
  Col,
  DatePicker,
  Dropdown,
  Form,
  Input,
  Modal,
  Radio,
  Row,
  Select,
  Space,
  Switch,
  Table,
  Tooltip,
  Tree,
  TreeSelect,
  Upload
} from 'antd';
import type { MenuProps } from 'antd';
import type { DataNode } from 'antd/es/tree';
import type { ColumnsType } from 'antd/es/table';
import type { UploadFile } from 'antd/es/upload/interface';
import type { Dayjs } from 'dayjs';
import {
  CheckCircleOutlined,
  DeleteOutlined,
  DownloadOutlined,
  DownOutlined,
  EditOutlined,
  InboxOutlined,
  KeyOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
  UploadOutlined
} from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import useDictOptions from '@/hooks/useDictOptions';
import { optionselect as getPostOptions } from '@/api/system/post';
import { listRole } from '@/api/system/role';
import type { RoleQuery, RoleVO } from '@/api/system/role/types';
import { addUser, changeUserStatus, delUser, deptTreeSelect, getUser, listUser, resetUserPwd, updateUser } from '@/api/system/user';
import type { UserForm, UserQuery, UserVO } from '@/api/system/user/types';
import type { DeptTreeVO } from '@/api/system/dept/types';
import type { PostVO } from '@/api/system/post/types';
import Pagination from '@/components/Pagination';
import RightToolbar, { type ToolbarColumn } from '@/components/RightToolbar';
import modal from '@/utils/modal';
import { addDateRange } from '@/utils/scaffold';
import request, { download } from '@/utils/request';

const initialQuery: UserQuery = {
  pageNum: 1,
  pageSize: 10,
  userName: '',
  nickName: '',
  phonenumber: '',
  status: '',
  deptId: '',
  roleId: ''
};

const initialForm: UserForm = {
  userId: undefined,
  deptId: undefined,
  userName: '',
  nickName: '',
  password: '',
  phonenumber: '',
  email: '',
  sex: '0',
  status: '0',
  remark: '',
  postIds: [],
  roleIds: []
};

const formatRange = (range: [Dayjs, Dayjs] | null) =>
  range ? [range[0].format('YYYY-MM-DD HH:mm:ss'), range[1].format('YYYY-MM-DD HH:mm:ss')] : [];

const toTreeData = (nodes: DeptTreeVO[]): DataNode[] =>
  nodes.map((node) => ({
    key: String(node.id),
    title: node.label,
    children: node.children?.length ? toTreeData(node.children) : undefined
  }));

const toTreeSelectData = (nodes: DeptTreeVO[]) =>
  nodes.map((node) => ({
    value: node.id,
    title: node.label,
    children: node.children?.length ? toTreeSelectData(node.children) : undefined
  }));

const filterDeptTree = (nodes: DeptTreeVO[], keyword: string): DeptTreeVO[] => {
  const normalizedKeyword = keyword.trim();
  if (!normalizedKeyword) {
    return nodes;
  }

  return nodes.reduce<DeptTreeVO[]>((result, node) => {
    const matchedChildren = node.children ? filterDeptTree(node.children, normalizedKeyword) : [];
    if (node.label.includes(normalizedKeyword) || matchedChildren.length > 0) {
      result.push({
        ...node,
        children: matchedChildren
      });
    }
    return result;
  }, []);
};

const filterDisabledDeptTree = (nodes: DeptTreeVO[]): DeptTreeVO[] =>
  nodes.reduce<DeptTreeVO[]>((result, node) => {
    if (node.disabled) {
      return result;
    }

    result.push({
      ...node,
      children: node.children?.length ? filterDisabledDeptTree(node.children) : undefined
    });

    return result;
  }, []);

const collectDeptKeys = (nodes: DeptTreeVO[]): string[] =>
  nodes.flatMap((node) => [String(node.id), ...(node.children ? collectDeptKeys(node.children) : [])]);

type UserTableColumn = ColumnsType<UserVO>[number] & {
  hidden?: boolean;
};

export default function UserPage() {
  const navigate = useNavigate();
  const [query, setQuery] = useState<UserQuery>(initialQuery);
  const [dateRange, setDateRange] = useState<[Dayjs, Dayjs] | null>(null);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [deptName, setDeptName] = useState('');
  const [list, setList] = useState<UserVO[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const [deptTree, setDeptTree] = useState<DeptTreeVO[]>([]);
  const [roleOptions, setRoleOptions] = useState<RoleVO[]>([]);
  const [postOptions, setPostOptions] = useState<PostVO[]>([]);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [pwdDialogOpen, setPwdDialogOpen] = useState(false);
  const [pwdSubmitting, setPwdSubmitting] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [activeUserId, setActiveUserId] = useState<string | number | undefined>();
  const [selectedDeptId, setSelectedDeptId] = useState<string>();
  const [importOpen, setImportOpen] = useState(false);
  const [importSubmitting, setImportSubmitting] = useState(false);
  const [importUpdateSupport, setImportUpdateSupport] = useState(false);
  const [importFileList, setImportFileList] = useState<UploadFile[]>([]);
  const [expandedDeptKeys, setExpandedDeptKeys] = useState<string[]>([]);
  const [autoExpandParent, setAutoExpandParent] = useState(false);
  const [columns, setColumns] = useState<ToolbarColumn[]>([
    { key: 'userId', label: '用户编号', visible: false },
    { key: 'userName', label: '用户名称', visible: true },
    { key: 'nickName', label: '用户昵称', visible: true },
    { key: 'deptName', label: '部门', visible: true },
    { key: 'phonenumber', label: '手机号码', visible: true },
    { key: 'status', label: '状态', visible: true },
    { key: 'createTime', label: '创建时间', visible: true }
  ]);
  const [form] = Form.useForm<UserForm>();
  const [pwdForm] = Form.useForm<{ password: string }>();
  const editingUserId = Form.useWatch('userId', form);
  const dict = useDictOptions('sys_normal_disable', 'sys_user_sex');
  const filteredDeptTree = useMemo(() => filterDeptTree(deptTree, deptName), [deptName, deptTree]);
  const enabledDeptTree = useMemo(() => filterDisabledDeptTree(deptTree), [deptTree]);

  const visibleColumnKeys = useMemo(() => new Set(columns.filter((item) => item.visible).map((item) => item.key)), [columns]);

  const loadDeptTree = useCallback(async () => {
    const response = await deptTreeSelect();
    setDeptTree(response.data);
  }, []);

  const loadList = useCallback(async (nextQuery: UserQuery = query, nextRange: [Dayjs, Dayjs] | null = dateRange) => {
    setLoading(true);
    try {
      const response = await listUser(addDateRange({ ...nextQuery }, formatRange(nextRange)));
      setList(response.rows);
      setTotal(response.total ?? response.rows.length);
    } finally {
      setLoading(false);
    }
  }, [dateRange, query]);

  const loadBaseOptions = useCallback(async (deptId?: string | number) => {
    const [roleResponse, postResponse] = await Promise.all([
      listRole({
        pageNum: 1,
        pageSize: 999,
        roleName: '',
        roleKey: '',
        status: '0'
      } as RoleQuery),
      getPostOptions(deptId)
    ]);
    setRoleOptions(roleResponse.rows);
    setPostOptions(postResponse.data);
  }, []);

  useEffect(() => {
    loadDeptTree();
    loadList(initialQuery, null);
    loadBaseOptions();
  }, [loadBaseOptions, loadDeptTree, loadList]);

  useEffect(() => {
    setExpandedDeptKeys(collectDeptKeys(deptTree));
    setAutoExpandParent(false);
  }, [deptTree]);

  useEffect(() => {
    if (deptName.trim()) {
      setExpandedDeptKeys(collectDeptKeys(filteredDeptTree));
      setAutoExpandParent(true);
      return;
    }

    setAutoExpandParent(false);
  }, [deptName, filteredDeptTree]);

  const moreActions: MenuProps['items'] = [
    {
      key: 'template',
      icon: <DownloadOutlined />,
      label: '下载模板'
    },
    {
      key: 'import',
      icon: <UploadOutlined />,
      label: '导入数据'
    },
    {
      key: 'export',
      icon: <DownloadOutlined />,
      label: '导出数据'
    }
  ];

  const handleEdit = useCallback(async (userId?: string | number) => {
    if (!userId) {
      return;
    }
    const response = await getUser(userId);
    const data = response.data;
    setRoleOptions(data.roles);
    setPostOptions(data.posts);
    form.resetFields();
    form.setFieldsValue({
      ...(data.user as unknown as UserForm),
      roleIds: data.roleIds || [],
      postIds: data.postIds || []
    });
    setDialogOpen(true);
  }, [form]);

  const handleDelete = useCallback(async (userId?: string | number | Array<string | number>) => {
    const target = userId || selectedIds;
    if (!target || (Array.isArray(target) && target.length === 0)) {
      modal.msgWarning('请选择要删除的用户');
      return;
    }
    const confirmed = await modal.confirm(`是否确认删除用户编号为 "${Array.isArray(target) ? target.join(',') : target}" 的数据项？`);
    if (!confirmed) {
      return;
    }
    await delUser(target);
    modal.msgSuccess('删除成功');
    setSelectedIds([]);
    loadList();
  }, [loadList, selectedIds]);

  const handleSubmit = useCallback(async () => {
    const values = await form.validateFields();
    setSubmitting(true);
    try {
      if (values.userId) {
        await updateUser(values);
      } else {
        await addUser(values);
      }
      modal.msgSuccess('操作成功');
      setDialogOpen(false);
      loadList();
    } finally {
      setSubmitting(false);
    }
  }, [form, loadList]);

  const handleAdd = useCallback(async () => {
    const response = await getUser();
    const data = response.data;
    setRoleOptions(data.roles);
    setPostOptions(data.posts);
    form.resetFields();
    form.setFieldsValue(initialForm);
    setDialogOpen(true);
  }, [form]);

  const handleQuery = useCallback(() => {
    const next = { ...query, pageNum: 1 };
    setQuery(next);
    loadList(next, dateRange);
  }, [dateRange, loadList, query]);

  const handleResetQuery = useCallback(() => {
    setQuery(initialQuery);
    setDateRange(null);
    setSelectedDeptId(undefined);
    loadList(initialQuery, null);
  }, [loadList]);

  const closeImportDialog = useCallback(() => {
    setImportOpen(false);
    setImportSubmitting(false);
    setImportUpdateSupport(false);
    setImportFileList([]);
  }, []);

  const handleImportSubmit = useCallback(async () => {
    if (importFileList.length === 0) {
      modal.msgWarning('请选择需要导入的文件');
      return;
    }

    const formData = new FormData();
    const file = importFileList[0].originFileObj;

    if (!file) {
      modal.msgWarning('未获取到上传文件');
      return;
    }

    formData.append('file', file);
    setImportSubmitting(true);

    try {
      const response = (await request({
        url: `/system/user/importData?updateSupport=${importUpdateSupport ? 1 : 0}`,
        method: 'post',
        headers: {
          repeatSubmit: false
        },
        data: formData
      })) as { msg?: string };

      closeImportDialog();
      Modal.info({
        title: '导入结果',
        width: 560,
        okText: '确定',
        content: (
          <div
            style={{ maxHeight: '50vh', overflowY: 'auto', paddingRight: 8 }}
            dangerouslySetInnerHTML={{ __html: response.msg || '导入成功' }}
          />
        )
      });
      loadList(initialQuery, null);
    } finally {
      setImportSubmitting(false);
    }
  }, [closeImportDialog, importFileList, importUpdateSupport, loadList]);

  const tableColumns = useMemo<ColumnsType<UserVO>>(() => {
    const nextColumns: UserTableColumn[] = [
      { title: '用户编号', dataIndex: 'userId', width: 100, align: 'center' as const, hidden: !visibleColumnKeys.has('userId') },
      { title: '用户名称', dataIndex: 'userName', width: 120, align: 'center' as const, hidden: !visibleColumnKeys.has('userName') },
      {
        title: '用户昵称',
        dataIndex: 'nickName',
        width: 120,
        align: 'center' as const,
        ellipsis: true,
        hidden: !visibleColumnKeys.has('nickName')
      },
      { title: '部门', dataIndex: 'deptName', width: 130, align: 'center' as const, ellipsis: true, hidden: !visibleColumnKeys.has('deptName') },
      { title: '手机号码', dataIndex: 'phonenumber', width: 120, align: 'center' as const, hidden: !visibleColumnKeys.has('phonenumber') },
      {
        title: '状态',
        dataIndex: 'status',
        width: 90,
        align: 'center' as const,
        hidden: !visibleColumnKeys.has('status'),
        render: (value: string, record) => (
          <Switch
            checked={value === '0'}
            disabled={record.userId === 1}
            onChange={async (checked) => {
              const nextStatus = checked ? '0' : '1';
              const confirmed = await modal.confirm(`确认要${nextStatus === '0' ? '启用' : '停用'} "${record.userName}" 用户吗？`);
              if (!confirmed) {
                return;
              }
              await changeUserStatus(record.userId, nextStatus);
              modal.msgSuccess('状态修改成功');
              loadList();
            }}
          />
        )
      },
      { title: '创建时间', dataIndex: 'createTime', width: 180, align: 'center' as const, hidden: !visibleColumnKeys.has('createTime') },
      {
        title: '操作',
        key: 'action',
        width: 180,
        align: 'center' as const,
        fixed: 'right' as const,
        render: (_, record) => (
          <Space size={4}>
            <Tooltip title="修改">
              <Button className="table-action-link" type="link" icon={<EditOutlined />} disabled={record.userId === 1} onClick={() => handleEdit(record.userId)} />
            </Tooltip>
            <Tooltip title="删除">
              <Button className="table-action-link" type="link" icon={<DeleteOutlined />} disabled={record.userId === 1} onClick={() => handleDelete(record.userId)} />
            </Tooltip>
            <Tooltip title="重置密码">
              <Button
                className="table-action-link"
                type="link"
                icon={<KeyOutlined />}
                disabled={record.userId === 1}
                onClick={() => {
                  setActiveUserId(record.userId);
                  pwdForm.setFieldsValue({ password: '' });
                  setPwdDialogOpen(true);
                }}
              />
            </Tooltip>
            <Tooltip title="分配角色">
              <Button
                className="table-action-link"
                type="link"
                icon={<CheckCircleOutlined />}
                disabled={record.userId === 1}
                onClick={() => navigate(`/system/user-auth/role/${record.userId}`)}
              />
            </Tooltip>
          </Space>
        )
      }
    ];

    return nextColumns.filter((column) => !column.hidden);
  }, [handleDelete, handleEdit, loadList, navigate, pwdForm, visibleColumnKeys]);

  return (
    <Row gutter={16}>
      <Col xs={24} xl={5}>
        <Card>
          <Input
            allowClear
            placeholder="请输入部门名称"
            prefix={<SearchOutlined />}
            value={deptName}
            onChange={(event) => setDeptName(event.target.value)}
          />
          <Tree
            style={{ marginTop: 12 }}
            treeData={toTreeData(filteredDeptTree)}
            virtual={false}
            blockNode
            expandedKeys={expandedDeptKeys}
            autoExpandParent={autoExpandParent}
            selectedKeys={selectedDeptId ? [selectedDeptId] : []}
            onExpand={(keys) => {
              setExpandedDeptKeys(keys as string[]);
              setAutoExpandParent(false);
            }}
            onSelect={(keys) => {
              const nextDeptId = keys[0] ? String(keys[0]) : undefined;
              setSelectedDeptId(nextDeptId);
              const next = {
                ...query,
                deptId: nextDeptId || ''
              };
              setQuery(next);
              loadList(next, dateRange);
            }}
          />
        </Card>
      </Col>
      <Col xs={24} xl={19}>
        <Space orientation="vertical" size={12} style={{ width: '100%' }}>
          {showSearch && (
            <Card>
              <Form layout="inline" className="query-form">
                <Row gutter={16} style={{ width: '100%' }}>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item label="用户名称" style={{ width: '100%', marginBottom: 12 }}>
                      <Input
                        allowClear
                        placeholder="请输入用户名称"
                        value={query.userName}
                        onChange={(event) => setQuery((prev) => ({ ...prev, userName: event.target.value }))}
                        onPressEnter={handleQuery}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item label="用户昵称" style={{ width: '100%', marginBottom: 12 }}>
                      <Input
                        allowClear
                        placeholder="请输入用户昵称"
                        value={query.nickName}
                        onChange={(event) => setQuery((prev) => ({ ...prev, nickName: event.target.value }))}
                        onPressEnter={handleQuery}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item label="手机号码" style={{ width: '100%', marginBottom: 12 }}>
                      <Input
                        allowClear
                        placeholder="请输入手机号码"
                        value={query.phonenumber}
                        onChange={(event) => setQuery((prev) => ({ ...prev, phonenumber: event.target.value }))}
                        onPressEnter={handleQuery}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item label="状态" style={{ width: '100%', marginBottom: 12 }}>
                      <Select
                        allowClear
                        style={{ width: '100%' }}
                        placeholder="用户状态"
                        value={query.status || undefined}
                        options={(dict.sys_normal_disable || []).map((item) => ({ label: item.label, value: item.value }))}
                        onChange={(value) => setQuery((prev) => ({ ...prev, status: value || '' }))}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={16} xl={8}>
                    <Form.Item label="创建时间" style={{ width: '100%', marginBottom: 0 }}>
                      <DatePicker.RangePicker
                        showTime
                        style={{ width: '100%' }}
                        value={dateRange}
                        onChange={(value) => setDateRange((value as [Dayjs, Dayjs]) || null)}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={8} xl={4}>
                    <Form.Item style={{ marginBottom: 0 }}>
                      <Space>
                        <Button
                          type="primary"
                          icon={<SearchOutlined />}
                          onClick={handleQuery}
                        >
                          搜索
                        </Button>
                        <Button icon={<ReloadOutlined />} onClick={handleResetQuery}>
                          重置
                        </Button>
                      </Space>
                    </Form.Item>
                  </Col>
                </Row>
              </Form>
            </Card>
          )}

          <Card>
            <div className="table-toolbar">
              <Space wrap className="toolbar-buttons">
                <Button className="btn-plain-primary" icon={<PlusOutlined />} onClick={handleAdd}>
                  新增
                </Button>
                <Button
                  className="btn-plain-success"
                  icon={<EditOutlined />}
                  onClick={() => handleEdit(selectedIds[0])}
                  disabled={selectedIds.length !== 1}
                >
                  修改
                </Button>
                <Button
                  className="btn-plain-danger"
                  icon={<DeleteOutlined />}
                  onClick={() => handleDelete()}
                  disabled={selectedIds.length === 0}
                >
                  删除
                </Button>
                <Dropdown
                  menu={{
                    items: moreActions,
                    onClick: ({ key }) => {
                      if (key === 'template') {
                        download('/system/user/importTemplate', {}, `user_template_${Date.now()}.xlsx`);
                      }
                      if (key === 'import') {
                        setImportOpen(true);
                      }
                      if (key === 'export') {
                        download('/system/user/export', addDateRange({ ...query }, formatRange(dateRange)), `user_${Date.now()}.xlsx`);
                      }
                    }
                  }}
                >
                  <Button>
                    更多
                    <DownOutlined />
                  </Button>
                </Dropdown>
              </Space>
              <div className="right-toolbar-wrap">
                <RightToolbar
                  search
                  showSearch={showSearch}
                  columns={columns}
                  onShowSearchChange={setShowSearch}
                  onQueryTable={() => loadList()}
                  onColumnsChange={setColumns}
                />
              </div>
            </div>

            <Table<UserVO>
              rowKey="userId"
              bordered
              loading={loading}
              columns={tableColumns}
              dataSource={list}
              pagination={false}
              rowSelection={{
                selectedRowKeys: selectedIds,
                columnWidth: 50,
                onChange: (keys) => setSelectedIds(keys as Array<string | number>)
              }}
            />

            <Pagination
              total={total}
              page={query.pageNum}
              limit={query.pageSize}
              onPageChange={({ page, limit }) => {
                const next = { ...query, pageNum: page, pageSize: limit };
                setQuery(next);
                loadList(next, dateRange);
              }}
            />
          </Card>
        </Space>
      </Col>

      <Modal
        width={860}
        open={dialogOpen}
        title={editingUserId ? '修改用户' : '新增用户'}
        confirmLoading={submitting}
        onCancel={() => setDialogOpen(false)}
        onOk={handleSubmit}
      >
        <Form form={form} layout="vertical" initialValues={initialForm}>
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item label="用户昵称" name="nickName" rules={[{ required: true, message: '用户昵称不能为空' }]}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="归属部门" name="deptId">
                <TreeSelect
                  treeData={toTreeSelectData(enabledDeptTree)}
                  placeholder="请选择归属部门"
                  allowClear
                  treeDefaultExpandAll
                  onChange={(value) => {
                    loadBaseOptions(value as string | number);
                  }}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item
                label="手机号码"
                name="phonenumber"
                rules={[{ pattern: /^1[3456789][0-9]\d{8}$/, message: '请输入正确的手机号码' }]}
              >
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="邮箱" name="email" rules={[{ type: 'email', message: '请输入正确的邮箱地址' }]}>
                <Input />
              </Form.Item>
            </Col>
            {!editingUserId && (
              <>
                <Col span={12}>
                  <Form.Item
                    label="用户名称"
                    name="userName"
                    rules={[
                      { required: true, message: '用户名称不能为空' },
                      { min: 2, max: 20, message: '用户名称长度必须介于 2 和 20 之间' }
                    ]}
                  >
                    <Input />
                  </Form.Item>
                </Col>
                <Col span={12}>
                  <Form.Item
                    label="用户密码"
                    name="password"
                    rules={[
                      { required: true, message: '用户密码不能为空' },
                      { min: 5, max: 20, message: '用户密码长度必须介于 5 和 20 之间' }
                    ]}
                  >
                    <Input.Password />
                  </Form.Item>
                </Col>
              </>
            )}
            <Col span={12}>
              <Form.Item label="用户性别" name="sex">
                <Radio.Group options={(dict.sys_user_sex || []).map((item) => ({ label: item.label, value: item.value }))} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="状态" name="status">
                <Radio.Group options={(dict.sys_normal_disable || []).map((item) => ({ label: item.label, value: item.value }))} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="岗位" name="postIds">
                <Select mode="multiple" options={postOptions.map((item) => ({ label: item.postName, value: item.postId }))} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="角色" name="roleIds" rules={[{ required: true, message: '用户角色不能为空' }]}>
                <Select mode="multiple" options={roleOptions.map((item) => ({ label: item.roleName, value: item.roleId }))} />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item label="备注" name="remark">
                <Input.TextArea rows={4} />
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Modal>

      <Modal
        open={importOpen}
        title="用户导入"
        width={400}
        okText="确定"
        cancelText="取消"
        confirmLoading={importSubmitting}
        okButtonProps={{ disabled: importFileList.length === 0 }}
        onCancel={closeImportDialog}
        onOk={handleImportSubmit}
      >
        <Upload.Dragger
          accept=".xlsx,.xls"
          maxCount={1}
          multiple={false}
          fileList={importFileList}
          beforeUpload={() => false}
          onChange={(info) => {
            setImportFileList(info.fileList.slice(-1));
          }}
        >
          <p className="ant-upload-drag-icon">
            <InboxOutlined />
          </p>
          <p className="ant-upload-text">将文件拖到此处，或点击上传</p>
          <p className="ant-upload-hint">仅允许导入 xls、xlsx 格式文件。</p>
        </Upload.Dragger>
        <div style={{ marginTop: 16 }}>
          <Checkbox checked={importUpdateSupport} onChange={(event) => setImportUpdateSupport(event.target.checked)}>
            是否更新已经存在的用户数据
          </Checkbox>
        </div>
        <div style={{ marginTop: 8, fontSize: 12, color: 'rgba(0, 0, 0, 0.45)' }}>
          下载模板后按格式填写，再执行导入。
          <Button
            type="link"
            size="small"
            style={{ paddingInline: 6 }}
            onClick={() => download('/system/user/importTemplate', {}, `user_template_${Date.now()}.xlsx`)}
          >
            下载模板
          </Button>
        </div>
      </Modal>

      <Modal
        open={pwdDialogOpen}
        title="重置密码"
        confirmLoading={pwdSubmitting}
        onCancel={() => setPwdDialogOpen(false)}
        onOk={async () => {
          const values = await pwdForm.validateFields();
          if (!activeUserId) {
            return;
          }
          setPwdSubmitting(true);
          try {
            await resetUserPwd(activeUserId, values.password);
            modal.msgSuccess(`修改成功，新密码是：${values.password}`);
            setPwdDialogOpen(false);
          } finally {
            setPwdSubmitting(false);
          }
        }}
      >
        <Form form={pwdForm} layout="vertical" initialValues={{ password: '' }}>
          <Form.Item
            label="新密码"
            name="password"
            rules={[
              { required: true, message: '新密码不能为空' },
              { min: 5, max: 20, message: '用户密码长度必须介于 5 和 20 之间' },
              { pattern: /^[^<>"'|\\]+$/, message: '不能包含非法字符：< > " \' \\ |' }
            ]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>
    </Row>
  );
}

// infoq-scaffold-frontend-vue/src/views/system/user/index.vue
<template>
  <div class="p-2">
    <el-row :gutter="20">
      <!-- 部门树 -->
      <el-col :lg="4" :xs="24" style="">
        <el-card shadow="hover">
          <el-input v-model="deptName" placeholder="请输入部门名称" prefix-icon="Search" clearable />
          <el-tree
            ref="deptTreeRef"
            class="mt-2"
            node-key="id"
            :data="deptOptions"
            :props="deptTreeProps"
            :expand-on-click-node="false"
            :filter-node-method="filterNode"
            highlight-current
            default-expand-all
            @node-click="handleNodeClick"
          />
        </el-card>
      </el-col>
      <el-col :lg="20" :xs="24">
        <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
          <div v-show="showSearch" class="mb-[10px]">
            <el-card shadow="hover">
              <el-form ref="queryFormRef" :model="queryParams" :inline="true">
                <el-form-item label="用户名称" prop="userName">
                  <el-input v-model="queryParams.userName" placeholder="请输入用户名称" clearable @keyup.enter="handleQuery" />
                </el-form-item>
                <el-form-item label="用户昵称" prop="nickName">
                  <el-input v-model="queryParams.nickName" placeholder="请输入用户昵称" clearable @keyup.enter="handleQuery" />
                </el-form-item>
                <el-form-item label="手机号码" prop="phonenumber">
                  <el-input v-model="queryParams.phonenumber" placeholder="请输入手机号码" clearable @keyup.enter="handleQuery" />
                </el-form-item>

                <el-form-item label="状态" prop="status">
                  <el-select v-model="queryParams.status" placeholder="用户状态" clearable>
                    <el-option v-for="dict in sys_normal_disable" :key="dict.value" :label="dict.label" :value="dict.value" />
                  </el-select>
                </el-form-item>
                <el-form-item label="创建时间" style="width: 308px">
                  <el-date-picker
                    v-model="dateRange"
                    value-format="YYYY-MM-DD HH:mm:ss"
                    type="daterange"
                    range-separator="-"
                    start-placeholder="开始日期"
                    end-placeholder="结束日期"
                    :default-time="[new Date(2000, 1, 1, 0, 0, 0), new Date(2000, 1, 1, 23, 59, 59)]"
                  ></el-date-picker>
                </el-form-item>
                <el-form-item>
                  <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
                  <el-button icon="Refresh" @click="resetQuery">重置</el-button>
                </el-form-item>
              </el-form>
            </el-card>
          </div>
        </transition>

        <el-card shadow="hover">
          <template #header>
            <el-row :gutter="10">
              <el-col :span="1.5">
                <el-button v-has-permi="['system:user:add']" type="primary" plain icon="Plus" @click="handleAdd()">新增</el-button>
              </el-col>
              <el-col :span="1.5">
                <el-button v-has-permi="['system:user:edit']" type="success" plain :disabled="single" icon="Edit" @click="handleUpdate()">
                  修改
                </el-button>
              </el-col>
              <el-col :span="1.5">
                <el-button v-has-permi="['system:user:remove']" type="danger" plain :disabled="multiple" icon="Delete" @click="handleDelete()">
                  删除
                </el-button>
              </el-col>
              <el-col :span="1.5">
                <el-dropdown class="mt-[1px]">
                  <el-button plain type="info">
                    更多
                    <el-icon class="el-icon--right"><arrow-down /></el-icon
                  ></el-button>
                  <template #dropdown>
                    <el-dropdown-menu>
                      <el-dropdown-item icon="Download" @click="importTemplate">下载模板</el-dropdown-item>
                      <!-- 注意 由于el-dropdown-item标签是延迟加载的 所以v-has-permi自定义标签不生效 需要使用v-if调用方法执行 -->
                      <el-dropdown-item v-if="checkPermi(['system:user:import'])" icon="Top" @click="handleImport">导入数据</el-dropdown-item>
                      <el-dropdown-item v-if="checkPermi(['system:user:export'])" icon="Download" @click="handleExport">导出数据</el-dropdown-item>
                    </el-dropdown-menu>
                  </template>
                </el-dropdown>
              </el-col>
              <right-toolbar v-model:show-search="showSearch" :columns="columns" :search="true" @query-table="getList"></right-toolbar>
            </el-row>
          </template>

          <el-table v-loading="loading" border :data="userList" @selection-change="handleSelectionChange">
            <el-table-column type="selection" width="50" align="center" />
            <el-table-column v-if="columns[0].visible" key="userId" label="用户编号" align="center" prop="userId" />
            <el-table-column v-if="columns[1].visible" key="userName" label="用户名称" align="center" prop="userName" :show-overflow-tooltip="true" />
            <el-table-column v-if="columns[2].visible" key="nickName" label="用户昵称" align="center" prop="nickName" :show-overflow-tooltip="true" />
            <el-table-column v-if="columns[3].visible" key="deptName" label="部门" align="center" prop="deptName" :show-overflow-tooltip="true" />
            <el-table-column v-if="columns[4].visible" key="phonenumber" label="手机号码" align="center" prop="phonenumber" width="120" />
            <el-table-column v-if="columns[5].visible" key="status" label="状态" align="center">
              <template #default="scope">
                <el-switch v-model="scope.row.status" active-value="0" inactive-value="1" @change="handleStatusChange(scope.row)"></el-switch>
              </template>
            </el-table-column>

            <el-table-column v-if="columns[6].visible" label="创建时间" align="center" prop="createTime" width="160">
              <template #default="scope">
                <span>{{ scope.row.createTime }}</span>
              </template>
            </el-table-column>

            <el-table-column label="操作" fixed="right" width="180" class-name="small-padding fixed-width">
              <template #default="scope">
                <el-tooltip v-if="scope.row.userId !== 1" content="修改" placement="top">
                  <el-button v-hasPermi="['system:user:edit']" link type="primary" icon="Edit" @click="handleUpdate(scope.row)"></el-button>
                </el-tooltip>
                <el-tooltip v-if="scope.row.userId !== 1" content="删除" placement="top">
                  <el-button v-hasPermi="['system:user:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)"></el-button>
                </el-tooltip>

                <el-tooltip v-if="scope.row.userId !== 1" content="重置密码" placement="top">
                  <el-button v-hasPermi="['system:user:resetPwd']" link type="primary" icon="Key" @click="handleResetPwd(scope.row)"></el-button>
                </el-tooltip>

                <el-tooltip v-if="scope.row.userId !== 1" content="分配角色" placement="top">
                  <el-button v-hasPermi="['system:user:edit']" link type="primary" icon="CircleCheck" @click="handleAuthRole(scope.row)"></el-button>
                </el-tooltip>
              </template>
            </el-table-column>
          </el-table>

          <pagination
            v-show="total > 0"
            v-model:page="queryParams.pageNum"
            v-model:limit="queryParams.pageSize"
            :total="total"
            @pagination="getList"
          />
        </el-card>
      </el-col>
    </el-row>

    <!-- 添加或修改用户配置对话框 -->
    <el-dialog ref="formDialogRef" v-model="dialog.visible" :title="dialog.title" width="600px" append-to-body @close="closeDialog">
      <el-form ref="userFormRef" :model="form" :rules="rules" label-width="80px">
        <el-row>
          <el-col :span="12">
            <el-form-item label="用户昵称" prop="nickName">
              <el-input v-model="form.nickName" placeholder="请输入用户昵称" maxlength="30" />
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.userId == null || form.userId != useUserStore().userId">
            <el-form-item label="归属部门" prop="deptId">
              <el-tree-select
                v-model="form.deptId"
                :data="enabledDeptOptions"
                :props="deptSelectProps"
                value-key="id"
                placeholder="请选择归属部门"
                check-strictly
                @change="handleDeptChange"
              />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12">
            <el-form-item label="手机号码" prop="phonenumber">
              <el-input v-model="form.phonenumber" placeholder="请输入手机号码" maxlength="11" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="form.email" placeholder="请输入邮箱" maxlength="50" />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12">
            <el-form-item v-if="form.userId == undefined" label="用户名称" prop="userName">
              <el-input v-model="form.userName" placeholder="请输入用户名称" maxlength="30" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item v-if="form.userId == undefined" label="用户密码" prop="password">
              <el-input v-model="form.password" placeholder="请输入用户密码" type="password" maxlength="20" show-password />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12">
            <el-form-item label="用户性别">
              <el-select v-model="form.sex" placeholder="请选择">
                <el-option v-for="dict in sys_user_sex" :key="dict.value" :label="dict.label" :value="dict.value"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="状态">
              <el-radio-group v-model="form.status">
                <el-radio v-for="dict in sys_normal_disable" :key="dict.value" :value="dict.value">{{ dict.label }}</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12" v-if="form.userId == null || form.userId != useUserStore().userId">
            <el-form-item label="岗位">
              <el-select v-model="form.postIds" multiple placeholder="请选择">
                <el-option
                  v-for="item in postOptions"
                  :key="item.postId"
                  :label="item.postName"
                  :value="item.postId"
                  :disabled="item.status == '1'"
                ></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.userId == null || form.userId != useUserStore().userId">
            <el-form-item label="角色" prop="roleIds">
              <el-select v-model="form.roleIds" filterable multiple placeholder="请选择">
                <el-option
                  v-for="item in roleOptions"
                  :key="item.roleId"
                  :label="item.roleName"
                  :value="item.roleId"
                  :disabled="item.status == '1'"
                ></el-option>
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="24">
            <el-form-item label="备注">
              <el-input v-model="form.remark" type="textarea" placeholder="请输入内容"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel()">取 消</el-button>
        </div>
      </template>
    </el-dialog>

    <!-- 用户导入对话框 -->
    <el-dialog v-model="upload.open" :title="upload.title" width="400px" append-to-body>
      <el-upload
        ref="uploadRef"
        :limit="1"
        accept=".xlsx, .xls"
        :headers="upload.headers"
        :action="upload.url + '?updateSupport=' + upload.updateSupport"
        :disabled="upload.isUploading"
        :on-progress="handleFileUploadProgress"
        :on-success="handleFileSuccess"
        :auto-upload="false"
        drag
      >
        <el-icon class="el-icon--upload">
          <i-ep-upload-filled />
        </el-icon>
        <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
        <template #tip>
          <div class="text-center el-upload__tip">
            <div class="el-upload__tip"><el-checkbox v-model="upload.updateSupport" />是否更新已经存在的用户数据</div>
            <span>仅允许导入xls、xlsx格式文件。</span>
            <el-link type="primary" :underline="false" style="font-size: 12px; vertical-align: baseline" @click="importTemplate">下载模板</el-link>
          </div>
        </template>
      </el-upload>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitFileForm">确 定</el-button>
          <el-button @click="upload.open = false">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="User" lang="ts">
import api from '@/api/system/user';
import { UserForm, UserQuery, UserVO } from '@/api/system/user/types';
import { DeptTreeVO, DeptVO } from '@/api/system/dept/types';
import { RoleVO } from '@/api/system/role/types';
import { PostVO } from '@/api/system/post/types';
import { globalHeaders } from '@/utils/request';
import { to } from 'await-to-js';
import { optionselect } from '@/api/system/post';
import { checkPermi } from '@/utils/permission';
import { useUserStore } from '@/store/modules/user';
import { toDictRefs } from '@/utils/dict';

const router = useRouter();
const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_normal_disable, sys_user_sex } = toDictRefs(
  (proxy?.useDict('sys_normal_disable', 'sys_user_sex') ?? {}) as Record<'sys_normal_disable' | 'sys_user_sex', DictDataOption[]>
);
const userList = ref<UserVO[]>();
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<number | string>>([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);
const dateRange = ref<[DateModelType, DateModelType]>(['', '']);
const deptName = ref('');
const deptOptions = ref<DeptTreeVO[]>([]);
const enabledDeptOptions = ref<DeptTreeVO[]>([]);
const initPassword = ref<string>('');
const postOptions = ref<PostVO[]>([]);
const roleOptions = ref<RoleVO[]>([]);
const deptTreeProps = { label: 'label', children: 'children' } as const;
const deptSelectProps = { value: 'id', label: 'label', children: 'children' } as const;
/*** 用户导入参数 */
const upload = reactive<ImportOption>({
  // 是否显示弹出层（用户导入）
  open: false,
  // 弹出层标题（用户导入）
  title: '',
  // 是否禁用上传
  isUploading: false,
  // 是否更新已经存在的用户数据
  updateSupport: 0,
  // 设置上传的请求头部
  headers: globalHeaders(),
  // 上传的地址
  url: import.meta.env.VITE_APP_BASE_API + '/system/user/importData'
});
// 列显隐信息
const columns = ref<FieldOption[]>([
  { key: 0, label: `用户编号`, visible: false, children: [] },
  { key: 1, label: `用户名称`, visible: true, children: [] },
  { key: 2, label: `用户昵称`, visible: true, children: [] },
  { key: 3, label: `部门`, visible: true, children: [] },
  { key: 4, label: `手机号码`, visible: true, children: [] },
  { key: 5, label: `状态`, visible: true, children: [] },
  { key: 6, label: `创建时间`, visible: true, children: [] }
]);

const deptTreeRef = ref<ElTreeInstance>();
const queryFormRef = ref<ElFormInstance>();
const userFormRef = ref<ElFormInstance>();
const uploadRef = ref<ElUploadInstance>();
const formDialogRef = ref<ElDialogInstance>();

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

const initFormData: UserForm = {
  userId: undefined,
  deptId: undefined,
  userName: '',
  nickName: undefined,
  password: '',
  phonenumber: undefined,
  email: undefined,
  sex: undefined,
  status: '0',
  remark: '',
  postIds: [],
  roleIds: []
};

const initData: PageData<UserForm, UserQuery> = {
  form: { ...initFormData },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    userName: '',
    phonenumber: '',
    status: '',
    deptId: '',
    roleId: ''
  },
  rules: {
    userName: [
      { required: true, message: '用户名称不能为空', trigger: 'blur' },
      {
        min: 2,
        max: 20,
        message: '用户名称长度必须介于 2 和 20 之间',
        trigger: 'blur'
      }
    ],
    nickName: [{ required: true, message: '用户昵称不能为空', trigger: 'blur' }],
    password: [
      { required: true, message: '用户密码不能为空', trigger: 'blur' },
      {
        min: 5,
        max: 20,
        message: '用户密码长度必须介于 5 和 20 之间',
        trigger: 'blur'
      },
      { pattern: /^[^<>"'|\\]+$/, message: '不能包含非法字符：< > " \' \\ |', trigger: 'blur' }
    ],
    email: [
      {
        type: 'email',
        message: '请输入正确的邮箱地址',
        trigger: ['blur', 'change']
      }
    ],
    phonenumber: [
      {
        pattern: /^1[3456789][0-9]\d{8}$/,
        message: '请输入正确的手机号码',
        trigger: 'blur'
      }
    ],
    roleIds: [{ required: true, message: '用户角色不能为空', trigger: 'blur' }]
  }
};
const data = reactive<PageData<UserForm, UserQuery>>(initData);

const { queryParams, form, rules } = toRefs<PageData<UserForm, UserQuery>>(data);

/** 通过条件过滤节点  */
const filterNode = (value: string, data: { label?: string }) => {
  if (!value) return true;
  return (data.label ?? '').indexOf(value) !== -1;
};
/** 根据名称筛选部门树 */
watchEffect(
  () => {
    deptTreeRef.value?.filter(deptName.value);
  },
  {
    flush: 'post' // watchEffect会在DOM挂载或者更新之前就会触发，此属性控制在DOM元素更新后运行
  }
);

/** 查询用户列表 */
const getList = async () => {
  loading.value = true;
  const res = await api.listUser(proxy?.addDateRange(queryParams.value, dateRange.value));
  loading.value = false;
  userList.value = res.rows;
  total.value = res.total;
};

/** 查询部门下拉树结构 */
const getDeptTree = async () => {
  const res = await api.deptTreeSelect();
  deptOptions.value = res.data;
  enabledDeptOptions.value = filterDisabledDept(res.data);
};

/** 过滤禁用的部门 */
const filterDisabledDept = (deptList: DeptTreeVO[]) => {
  return deptList.filter((dept) => {
    if (dept.disabled) {
      return false;
    }
    if (dept.children && dept.children.length) {
      dept.children = filterDisabledDept(dept.children);
    }
    return true;
  });
};

/** 节点单击事件 */
const handleNodeClick = (data: DeptVO) => {
  queryParams.value.deptId = data.id;
  handleQuery();
};

/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  dateRange.value = ['', ''];
  queryFormRef.value?.resetFields();
  queryParams.value.pageNum = 1;
  queryParams.value.deptId = undefined;
  deptTreeRef.value?.setCurrentKey(undefined);
  handleQuery();
};

/** 删除按钮操作 */
const handleDelete = async (row?: UserVO) => {
  const userIds = row?.userId || ids.value;
  const [err] = await to(proxy?.$modal.confirm('是否确认删除用户编号为"' + userIds + '"的数据项？'));
  if (!err) {
    await api.delUser(userIds);
    await getList();
    proxy?.$modal.msgSuccess('删除成功');
  }
};

/** 用户状态修改  */
const handleStatusChange = async (row: UserVO) => {
  const text = row.status === '0' ? '启用' : '停用';
  try {
    await proxy?.$modal.confirm('确认要"' + text + '""' + row.userName + '"用户吗?');
    await api.changeUserStatus(row.userId, row.status);
    proxy?.$modal.msgSuccess(text + '成功');
  } catch (err) {
    row.status = row.status === '0' ? '1' : '0';
  }
};
/** 跳转角色分配 */
const handleAuthRole = (row: UserVO) => {
  const userId = row.userId;
  router.push('/system/user-auth/role/' + userId);
};

/** 重置密码按钮操作 */
const handleResetPwd = async (row: UserVO) => {
  const [err, res] = await to(
    ElMessageBox.prompt('请输入"' + row.userName + '"的新密码', '提示', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      closeOnClickModal: false,
      inputPattern: /^.{5,20}$/,
      inputErrorMessage: '用户密码长度必须介于 5 和 20 之间',
      inputValidator: (value) => {
        if (/<|>|"|'|\||\\/.test(value)) {
          return '不能包含非法字符：< > " \' \\ |';
        }
      }
    })
  );
  if (!err && res) {
    await api.resetUserPwd(row.userId, res.value);
    proxy?.$modal.msgSuccess('修改成功，新密码是：' + res.value);
  }
};

/** 选择条数  */
const handleSelectionChange = (selection: UserVO[]) => {
  ids.value = selection.map((item) => item.userId);
  single.value = selection.length != 1;
  multiple.value = !selection.length;
};

/** 导入按钮操作 */
const handleImport = () => {
  upload.title = '用户导入';
  upload.open = true;
};
/** 导出按钮操作 */
const handleExport = () => {
  proxy?.download(
    'system/user/export',
    {
      ...queryParams.value
    },
    `user_${new Date().getTime()}.xlsx`
  );
};
/** 下载模板操作 */
const importTemplate = () => {
  proxy?.download('system/user/importTemplate', {}, `user_template_${new Date().getTime()}.xlsx`);
};

/**文件上传中处理 */
const handleFileUploadProgress = () => {
  upload.isUploading = true;
};
/** 文件上传成功处理 */
const handleFileSuccess = (response: { msg: string }, file: UploadFile) => {
  upload.open = false;
  upload.isUploading = false;
  uploadRef.value?.handleRemove(file);
  ElMessageBox.alert("<div style='overflow: auto;overflow-x: hidden;max-height: 70vh;padding: 10px 20px 0;'>" + response.msg + '</div>', '导入结果', {
    dangerouslyUseHTMLString: true
  });
  getList();
};

/** 提交上传文件 */
function submitFileForm() {
  uploadRef.value?.submit();
}

/** 重置操作表单 */
const reset = () => {
  form.value = { ...initFormData };
  userFormRef.value?.resetFields();
};
/** 取消按钮 */
const cancel = () => {
  dialog.visible = false;
  reset();
};

/** 新增按钮操作 */
const handleAdd = async () => {
  reset();
  const { data } = await api.getUser();
  dialog.visible = true;
  dialog.title = '新增用户';
  postOptions.value = data.posts;
  roleOptions.value = data.roles;
  form.value.password = initPassword.value.toString();
};

/** 修改按钮操作 */
const handleUpdate = async (row?: UserForm) => {
  reset();
  const userId = row?.userId || ids.value[0];
  const { data } = await api.getUser(userId);
  dialog.visible = true;
  dialog.title = '修改用户';
  Object.assign(form.value, data.user);
  postOptions.value = data.posts;
  roleOptions.value = Array.from(new Map([...data.roles, ...data.user.roles].map((role) => [role.roleId, role])).values());
  form.value.postIds = data.postIds;
  form.value.roleIds = data.roleIds;
  form.value.password = '';
};

/** 提交按钮 */
const submitForm = () => {
  userFormRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      if (form.value.userId) {
        // 自己编辑自己的情况下 不允许编辑角色部门岗位
        if (form.value.userId == useUserStore().userId) {
          form.value.roleIds = null;
          form.value.deptId = null;
          form.value.postIds = null;
        }
        await api.updateUser(form.value);
      } else {
        await api.addUser(form.value);
      }
      proxy?.$modal.msgSuccess('操作成功');
      dialog.visible = false;
      await getList();
    }
  });
};

/**
 * 关闭用户弹窗
 */
const closeDialog = () => {
  dialog.visible = false;
  resetForm();
};

/**
 * 重置表单
 */
const resetForm = () => {
  userFormRef.value?.resetFields();
  userFormRef.value?.clearValidate();

  form.value.id = undefined;
  form.value.status = '1';
};
onMounted(() => {
  getDeptTree(); // 初始化部门数据
  getList(); // 初始化列表数据
  proxy?.getConfigKey('sys.user.initPassword').then((response) => {
    initPassword.value = response.data;
  });
});

async function handleDeptChange(value: number | string) {
  const response = await optionselect(value);
  postOptions.value = response.data;
  form.value.postIds = [];
}
</script>
